spring:
  application:
    name: product-service

  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: ${PRODUCT_SERVER_PORT:8081}
  shutdown: graceful
  forward-headers-strategy: framework

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus